spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: afaf45225
spring.datasource.password: afaf45225
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
